package org.molokosoft.decisionengine.jobs

import org.molokosoft.decisionengine.database.tables.articles.DailyArticleEntry
import org.molokosoft.decisionengine.repositories.articles.ArticlesRepository
import org.molokosoft.decisionengine.services.articles.ArticlesService

class DailyArticleJob(
    private val articlesRepository: ArticlesRepository,
    private val articlesService: ArticlesService
) : Job {
    override suspend fun execute() {
        val dailyArticle = articlesService.dailyArticle(
            topics.random()
        )

        if (dailyArticle == null)
            return

        val dailyArticleEntry = DailyArticleEntry(
            title =  dailyArticle.title,
            topic = dailyArticle.topic,
            readingTimeMinutes = dailyArticle.readingTimeMinutes,
            summary = dailyArticle.summary,
            content = dailyArticle.content,
            takeAwayPoints = dailyArticle.takeAwayPoints
        )

        articlesRepository.insertDailyArticle(dailyArticleEntry)
    }

    private val topics = listOf(
        "Confirmation Bias",
        "Anchoring Bias",
        "Availability Heuristic",
        "Loss Aversion",
        "Sunk Cost Fallacy",
        "Framing Effect",
        "Status Quo Bias",
        "Halo Effect",
        "Horn Effect",
        "Overconfidence Bias",
        "Optimism Bias",
        "Negativity Bias",
        "Recency Bias",
        "Hindsight Bias",
        "Self-Serving Bias",
        "Dunning-Kruger Effect",
        "Survivorship Bias",
        "Authority Bias",
        "Bandwagon Effect",
        "Endowment Effect",
        "Choice Overload",
        "Decision Fatigue",
        "Default Effect",
        "Mere Exposure Effect",
        "IKEA Effect",
        "Scarcity Effect",
        "Peak-End Rule",
        "Affect Heuristic",
        "Base Rate Neglect",
        "Gambler's Fallacy",
        "Opportunity Cost",
        "First Principles Thinking",
        "Second-Order Thinking",
        "Inversion",
        "Probabilistic Thinking",
        "Expected Value",
        "Bayesian Thinking",
        "Pareto Principle",
        "Occam's Razor",
        "Hanlon's Razor",
        "Circle of Competence",
        "Margin of Safety",
        "Thinking in Bets",
        "Regret Minimization Framework",
        "Cost-Benefit Analysis",
        "Reversible vs. Irreversible Decisions",
        "Trade-Off Thinking",
        "Long-Term vs. Short-Term Thinking",
        "The Power of Small Decisions",
        "Delayed Gratification",
        "Emotional Decision Making",
        "Intuition vs. Analysis",
        "Stress and Decision Quality",
        "Fear of Missing Out (FOMO)",
        "Fear of Failure",
        "Perfectionism",
        "Analysis Paralysis",
        "Cognitive Load",
        "Mental Energy Management",
        "Habit-Based Decisions",
        "Goal Conflict",
        "Identity-Based Decisions",
        "Values-Based Decision Making",
        "Emotional Intelligence in Decisions",
        "Resilience After Bad Decisions",
        "Learning From Mistakes",
        "Escalation of Commitment",
        "Decision Confidence",
        "The Power of Saying No",
        "Prioritization Techniques",
        "Active Listening",
        "Asking Better Questions",
        "Constructive Disagreement",
        "Negotiation Fundamentals",
        "Win-Win Thinking",
        "Perspective Taking",
        "Empathy in Decision Making",
        "Giving and Receiving Feedback",
        "Groupthink",
        "Social Proof",
        "Risk vs. Uncertainty",
        "Black Swan Events",
        "Expected vs. Unexpected Outcomes",
        "Scenario Planning",
        "Optionality",
        "Decision Trees",
        "Diversification",
        "Thinking in Systems",
        "Feedback Loops",
        "Leverage Points",
        "Incentives Shape Behavior",
        "Time Horizons",
        "Compounding Effects",
        "Simplicity in Decisions",
        "The Power of Reflection",
        "Daily Decision Journaling",
        "Common Logical Fallacies",
        "Cognitive Biases in Investing",
        "Building Better Decision Habits",
        "What Makes a Good Decision?",
        "False Dilemma",
        "Straw Man Fallacy",
        "Slippery Slope",
        "Ad Hominem",
        "Appeal to Authority",
        "Appeal to Emotion",
        "Appeal to Popularity",
        "False Cause",
        "Correlation vs. Causation",
        "Cherry Picking",
        "Burden of Proof",
        "Circular Reasoning",
        "False Analogy",
        "Red Herring",
        "Tu Quoque",
        "Appeal to Ignorance",
        "Zero-Sum Thinking",
        "Abundance Mindset",
        "Scarcity Mindset",
        "Growth Mindset",
        "Fixed Mindset",
        "Decision Hygiene",
        "Thinking Clearly Under Pressure",
        "Managing Uncertainty",
        "Confidence vs. Competence",
        "The Planning Fallacy",
        "Outcome Bias",
        "Omission Bias",
        "Action Bias",
        "Projection Bias",
        "False Consensus Effect",
        "Curse of Knowledge",
        "Naive Realism",
        "Reactance",
        "Decoy Effect",
        "Contrast Effect",
        "Spotlight Effect",
        "Illusion of Control",
        "Hot-Hand Fallacy",
        "Selection Bias",
        "Sampling Bias",
        "Confirmation Traps",
        "Pre-Mortem Analysis",
        "Post-Mortem Analysis",
        "Decision Checklists",
        "Mental Models",
        "Systems Thinking",
        "Root Cause Analysis",
        "The Five Whys",
        "OODA Loop",
        "Eisenhower Matrix",
        "80/20 Thinking at Work",
        "Time Blocking",
        "Opportunity Recognition",
        "Recognizing Hidden Costs",
        "Managing Trade-Offs",
        "Decision Speed vs. Decision Quality",
        "Good Decisions, Bad Outcomes",
        "Bad Decisions, Good Outcomes",
        "Luck vs. Skill",
        "Randomness in Life",
        "The Value of Patience",
        "Strategic Patience",
        "Instant Gratification",
        "Long-Term Incentives",
        "Thinking About Consequences",
        "Future Self Thinking",
        "Opportunity Bias",
        "Avoiding Knee-Jerk Reactions",
        "The Power of Pause",
        "Listening Before Judging",
        "Asking Why Before How",
        "The Value of Curiosity",
        "Recognizing Emotional Triggers",
        "Building Rational Habits",
        "Thinking in Probabilities",
        "Estimating Risks",
        "Expected Regret",
        "Decision Thresholds",
        "When to Trust Your Gut",
        "When Not to Trust Your Gut",
        "The Cost of Indecision",
        "The Power of Commitment",
        "Knowing When to Quit",
        "Avoiding Escalation",
        "Building Better Habits",
        "Breaking Bad Habits",
        "Micro Decisions",
        "Keystone Habits",
        "Decision Journals",
        "Reflective Thinking",
        "Cognitive Flexibility",
        "Intellectual Humility",
        "Being Open to Being Wrong",
        "Changing Your Mind",
        "The Value of Skepticism",
        "Healthy Doubt",
        "Learning from Feedback",
        "Making Better Financial Decisions",
        "Making Better Career Decisions",
        "Making Better Relationship Decisions",
        "Making Better Health Decisions",
        "Consumer Psychology",
        "Marketing Tricks That Influence Decisions",
        "Price Perception",
        "Anchoring in Negotiation",
        "Negotiating with Confidence",
        "The Psychology of Persuasion",
        "Reciprocity Principle",
        "Commitment and Consistency",
        "Social Influence",
        "Decision Making Under Stress",
        "Managing Information Overload",
        "Avoiding Burnout Decisions",
        "Recognizing Manipulation",
        "Separating Facts from Opinions",
        "Evidence-Based Thinking",
        "Critical Thinking in Everyday Life",
        "Learning to Say 'I Don't Know'",
        "Building Better Judgment",
        "Thinking Like an Investor",
        "Thinking Like a Scientist",
        "Thinking Like a CEO",
        "Thinking Before Reacting",
        "Clarity Before Action",
        "Making Fewer, Better Decisions"
    )
}